package com.processm.processminterpreter.pql.visitor

import QLParser
import QLParserBaseVisitor
import com.processm.processminterpreter.pql.CypherQuery
import com.processm.processminterpreter.pql.StandardAttributeMapper
import com.processm.processminterpreter.pql.StandardAttributeMapper.Scope
import com.processm.processminterpreter.pql.model.Query
import org.slf4j.LoggerFactory

/**
 * ANTLR Visitor that translates ProcessM PQL AST to Neo4j Cypher queries
 *
 * This visitor walks through the Abstract Syntax Tree (AST) generated by ANTLR
 * from ProcessM's QL grammar and converts it into Neo4j Cypher queries with parameters.
 *
 * Key Features:
 * - SELECT queries (read_query)
 * - DELETE queries (delete_query)
 * - WHERE clauses with complex logic expressions
 * - Arithmetic expressions
 * - Scalar and aggregate functions
 * - SCOPE prefixes (log:/trace:/event:)
 * - GROUP BY, ORDER BY, LIMIT, OFFSET
 *
 * @param logId Optional log ID to filter results to a specific log
 */
class QLToCypherVisitor(
    private val logId: String? = null,
    private val defaultTraceLimit: Int? = null,
) : QLParserBaseVisitor<Any>() {
    private val logger = LoggerFactory.getLogger(QLToCypherVisitor::class.java)
    private val parameters = mutableMapOf<String, Any>()
    private var paramCounter = 0

    // Track current scope context for field resolution
    private var currentScope: Scope = Scope.Event
    private val scopeStack = mutableListOf<Scope>()

    // Track all scopes actually used in the query (after hoisting)
    // This is needed to build the correct MATCH clause
    private val usedScopes = mutableSetOf<Scope>()

    // ========================================
    // ENTRY POINT
    // ========================================

    /**
     * Entry point - visits the root query node
     * query: read_query EOF | delete_query EOF
     *
     * New approach: Use QueryBuilder to parse into Query object first,
     * then translate Query object to Cypher.
     */
    override fun visitQuery(ctx: QLParser.QueryContext): CypherQuery {
        logger.debug("Visiting query: ${ctx.text}")

        // Step 1: Use QueryBuilder to parse into Query object
        val queryBuilder = QueryBuilder()
        val query = queryBuilder.build(ctx, ctx.text)

        // Step 2: Translate Query object to Cypher
        return translateQueryToCypher(query)
    }

    // ========================================
    // DEPRECATED: OLD VISITOR CODE - NOT USED
    // ========================================
    // The code below (lines 69-721) is deprecated and no longer used.
    // It was the old ANTLR visitor-based translation approach, now replaced
    // by the Query model approach (translateQueryToCypher and related methods).
    // This code can be safely removed in the future.
    // ========================================

    /**
     * Legacy entry point methods - kept for backward compatibility
     * and internal use for expression translation.
     */
    @Deprecated("Not used - replaced by Query model approach")
    private fun visitRead_query_legacy(ctx: QLParser.Read_queryContext): CypherQuery = visitRead_query(ctx)

    private fun visitDelete_query_legacy(ctx: QLParser.Delete_queryContext): CypherQuery = visitDelete_query(ctx)

    // ========================================
    // READ QUERY (SELECT)
    // ========================================

    /**
     * read_query: select where? group_by? order_by? limit? offset?
     */
    override fun visitRead_query(ctx: QLParser.Read_queryContext): CypherQuery {
        logger.debug("Visiting read_query")

        // Clear used scopes from any previous query
        usedScopes.clear()

        // Determine scope from SELECT clause
        val selectCtx = ctx.select()
        determineScope(selectCtx)

        // Build components - dispatch to correct labeled alternative
        val selectClause = visit(selectCtx) as String
        val whereClause = ctx.where()?.let { visitWhere(it) }
        val groupByClause = ctx.group_by()?.let { visitGroup_by(it) }
        val orderByClause = ctx.order_by()?.let { visitOrder_by(it) }
        val limitClause = ctx.limit()?.let { visitLimit(it) }
        val offsetClause = ctx.offset()?.let { visitOffset(it) }

        logger.debug("Parsed - Scope: {}, SELECT: {}, WHERE: {}", currentScope, selectClause, whereClause)

        return buildReadQuery(
            scope = currentScope,
            selectClause = selectClause,
            whereClause = whereClause,
            groupByClause = groupByClause,
            orderByClause = orderByClause,
            limitClause = limitClause,
            offsetClause = offsetClause,
        )
    }

    /**
     * Determine query scope from SELECT clause or context
     * Looks for SCOPE prefixes in column list
     */
    private fun determineScope(selectCtx: QLParser.SelectContext) {
        // Try to find scope from column_list
        val text = selectCtx.text.lowercase()

        currentScope =
            when {
                text.contains("event:") || text.contains("e:") -> Scope.Event
                text.contains("trace:") || text.contains("t:") -> Scope.Trace
                text.contains("log:") || text.contains("l:") -> Scope.Log
                else -> Scope.Event // Default to event
            }

        logger.debug("Determined scope: {}", currentScope)
    }

    /**
     * select_all_implicit
     */
    override fun visitSelect_all_implicit(ctx: QLParser.Select_all_implicitContext): String = "*"

    /**
     * select_all: SELECT '*'
     */
    override fun visitSelect_all(ctx: QLParser.Select_allContext): String = "*"

    /**
     * select_column_list: SELECT column_list
     */
    override fun visitSelect_column_list(ctx: QLParser.Select_column_listContext): String {
        // Process column_list - need to handle both labeled alternatives
        return when (val columnListCtx = ctx.column_list()) {
            is QLParser.Scoped_select_allContext -> visitScoped_select_all(columnListCtx)
            is QLParser.Column_list_arith_expr_rootContext -> visitColumn_list_arith_expr_root(columnListCtx)
            else -> throw IllegalStateException("Unknown column_list type")
        }
    }

    /**
     * scoped_select_all: SCOPE:*
     */
    override fun visitScoped_select_all(ctx: QLParser.Scoped_select_allContext): String {
        // SCOPE:* - return all fields for that scope
        return "*"
    }

    /**
     * column_list_arith_expr_root: arith_expr_root | arith_expr_root ',' column_list
     */
    override fun visitColumn_list_arith_expr_root(ctx: QLParser.Column_list_arith_expr_rootContext): String {
        // One or more expressions
        val expressions = mutableListOf<String>()
        var current: QLParser.Column_listContext? = ctx

        while (current != null) {
            if (current is QLParser.Column_list_arith_expr_rootContext) {
                val expr = visitArith_expr_root(current.arith_expr_root())
                expressions.add(expr)
                current = current.column_list()
            } else if (current is QLParser.Scoped_select_allContext) {
                expressions.add("*")
                break
            } else {
                break
            }
        }

        return expressions.joinToString(", ")
    }

    override fun visitArith_expr_root(ctx: QLParser.Arith_expr_rootContext): String = visitArith_expr(ctx.arith_expr())

    // ========================================
    // DELETE QUERY
    // ========================================

    /**
     * delete_query: delete where? order_by? limit? offset?
     */
    override fun visitDelete_query(ctx: QLParser.Delete_queryContext): CypherQuery {
        logger.debug("Visiting delete_query")

        val deleteCtx = ctx.delete()
        val scope = extractScopeFromDelete(deleteCtx)
        currentScope = scope

        val whereClause = ctx.where()?.let { visitWhere(it) }
        val orderByClause = ctx.order_by()?.let { visitOrder_by(it) }
        val limitClause = ctx.limit()?.let { visitLimit(it) }
        val offsetClause = ctx.offset()?.let { visitOffset(it) }

        return buildDeleteQuery(
            scope = scope,
            whereClause = whereClause,
            orderByClause = orderByClause,
            limitClause = limitClause,
            offsetClause = offsetClause,
        )
    }

    /**
     * delete: DELETE SCOPE?
     */
    private fun extractScopeFromDelete(ctx: QLParser.DeleteContext): Scope {
        val scopeText = ctx.SCOPE()?.text?.lowercase()
        return when (scopeText) {
            "log", "l" -> Scope.Log
            "trace", "t" -> Scope.Trace
            "event", "e" -> Scope.Event
            null -> Scope.Event // Default
            else -> Scope.Event
        }
    }

    // ========================================
    // WHERE CLAUSE
    // ========================================

    /**
     * where: WHERE logic_expr
     */
    override fun visitWhere(ctx: QLParser.WhereContext): String = visitLogic_expr(ctx.logic_expr())

    /**
     * logic_expr: Complex logical expressions with proper precedence
     *
     * Precedence (high to low):
     * 1. Parentheses
     * 2. IN, NOT IN, MATCHES, LIKE
     * 3. Comparison operators
     * 4. NULL checks
     * 5. NOT
     * 6. AND
     * 7. OR
     */
    override fun visitLogic_expr(ctx: QLParser.Logic_exprContext): String =
        when {
            // Parenthesized expression
            ctx.logic_expr().size == 1 && ctx.text.startsWith("(") -> {
                "(${visitLogic_expr(ctx.logic_expr(0))})"
            }

            // IN / NOT IN
            ctx.OP_IN() != null || ctx.OP_NOT_IN() != null -> {
                val leftExpr = visitArith_expr(ctx.arith_expr(0))
                val operator = if (ctx.OP_IN() != null) "IN" else "NOT IN"
                val inList = visitIn_list(ctx.in_list())
                val paramName = nextParamName()
                parameters[paramName] = inList
                "$leftExpr $operator \$$paramName"
            }

            // MATCHES (regex) / LIKE
            ctx.OP_MATCHES() != null || ctx.OP_LIKE() != null -> {
                val leftExpr = visitArith_expr(ctx.arith_expr(0))
                val pattern = removeQuotes(ctx.STRING().text)
                val paramName = nextParamName()

                if (ctx.OP_MATCHES() != null) {
                    // MATCHES -> Neo4j =~ (regex)
                    parameters[paramName] = pattern
                    "$leftExpr =~ \$$paramName"
                } else {
                    // LIKE -> Neo4j CONTAINS
                    parameters[paramName] = pattern
                    "$leftExpr CONTAINS \$$paramName"
                }
            }

            // Comparison operators
            ctx.OP_LT() != null || ctx.OP_LE() != null || ctx.OP_EQ() != null ||
                ctx.OP_NEQ() != null || ctx.OP_GT() != null || ctx.OP_GE() != null -> {
                val leftExpr = visitArith_expr(ctx.arith_expr(0))
                val rightExpr = visitArith_expr(ctx.arith_expr(1))
                val operator =
                    when {
                        ctx.OP_LT() != null -> "<"
                        ctx.OP_LE() != null -> "<="
                        ctx.OP_EQ() != null -> "="
                        ctx.OP_NEQ() != null -> "<>"
                        ctx.OP_GT() != null -> ">"
                        ctx.OP_GE() != null -> ">="
                        else -> throw IllegalStateException("Unknown comparison operator")
                    }
                "$leftExpr $operator $rightExpr"
            }

            // NULL checks
            ctx.OP_IS_NULL() != null || ctx.OP_IS_NOT_NULL() != null -> {
                val expr = visitArith_expr(ctx.arith_expr(0))
                if (ctx.OP_IS_NULL() != null) {
                    "$expr IS NULL"
                } else {
                    "$expr IS NOT NULL"
                }
            }

            // NOT
            ctx.OP_NOT() != null -> {
                "NOT (${visitLogic_expr(ctx.logic_expr(0))})"
            }

            // AND
            ctx.OP_AND() != null -> {
                val left = visitLogic_expr(ctx.logic_expr(0))
                val right = visitLogic_expr(ctx.logic_expr(1))
                "$left AND $right"
            }

            // OR
            ctx.OP_OR() != null -> {
                val left = visitLogic_expr(ctx.logic_expr(0))
                val right = visitLogic_expr(ctx.logic_expr(1))
                "$left OR $right"
            }

            else -> throw IllegalStateException("Unknown logic_expr type: ${ctx.text}")
        }

    /**
     * in_list: '(' id_or_scalar_list ')'
     */
    override fun visitIn_list(ctx: QLParser.In_listContext): List<Any> = visitId_or_scalar_list(ctx.id_or_scalar_list())

    /**
     * id_or_scalar_list: (ID | scalar) (',' (ID | scalar))*
     */
    override fun visitId_or_scalar_list(ctx: QLParser.Id_or_scalar_listContext): List<Any> {
        val values = mutableListOf<Any>()

        // Collect all IDs and scalars
        ctx.ID().forEach { values.add(it.text) }
        ctx.scalar().forEach { values.add(visitScalar(it)!!) }

        return values
    }

    // ========================================
    // ARITHMETIC EXPRESSIONS
    // ========================================

    /**
     * arith_expr: Arithmetic expressions with operator precedence
     *
     * Precedence (high to low):
     * 1. Parentheses
     * 2. Multiplication, Division
     * 3. Addition, Subtraction
     * 4. Functions, Identifiers, Scalars
     */
    override fun visitArith_expr(ctx: QLParser.Arith_exprContext): String =
        when {
            // Parenthesized expression
            ctx.arith_expr().size == 1 && ctx.text.startsWith("(") -> {
                "(${visitArith_expr(ctx.arith_expr(0)) as String})"
            }

            // Multiplication or Division
            ctx.text.contains("*") || ctx.text.contains("/") -> {
                val left = visitArith_expr(ctx.arith_expr(0)) as String
                val right = visitArith_expr(ctx.arith_expr(1)) as String
                val operator = if (ctx.text.contains("*")) "*" else "/"
                "$left $operator $right"
            }

            // Addition or Subtraction
            ctx.text.contains("+") || (ctx.text.contains("-") && ctx.arith_expr().size > 1) -> {
                val left = visitArith_expr(ctx.arith_expr(0)) as String
                val right = visitArith_expr(ctx.arith_expr(1)) as String
                val operator = if (ctx.text.contains("+")) "+" else "-"
                "$left $operator $right"
            }

            // Function
            ctx.func() != null -> {
                visitFunc(ctx.func()) as String
            }

            // Identifier (field reference)
            ctx.ID() != null -> {
                translateFieldReference(ctx.ID().text)
            }

            // Scalar literal
            ctx.scalar() != null -> {
                val scalarValue = visitScalar(ctx.scalar())
                val paramName = nextParamName()
                parameters[paramName] = scalarValue!!
                "\$$paramName"
            }

            else -> throw IllegalStateException("Unknown arith_expr type: ${ctx.text}")
        }

    /**
     * func: FUNC_SCALAR0 '()' | FUNC_SCALAR1 '(' arith_expr ')' | FUNC_AGGR '(' ID ')'
     */
    override fun visitFunc(ctx: QLParser.FuncContext): String =
        when {
            // Zero-argument function (e.g., now())
            ctx.FUNC_SCALAR0() != null -> {
                val funcName = extractFunctionName(ctx.FUNC_SCALAR0().text)
                translateScalarFunction0(funcName)
            }

            // Single-argument scalar function (e.g., year(timestamp))
            ctx.FUNC_SCALAR1() != null -> {
                val funcName = extractFunctionName(ctx.FUNC_SCALAR1().text)
                val arg = visitArith_expr(ctx.arith_expr()) as String
                translateScalarFunction1(funcName, arg)
            }

            // Aggregate function (e.g., count(id))
            ctx.FUNC_AGGR() != null -> {
                val funcName = extractFunctionName(ctx.FUNC_AGGR().text)
                val arg = translateFieldReference(ctx.ID().text)
                translateAggregateFunction(funcName, arg)
            }

            else -> throw IllegalStateException("Unknown function type")
        }

    private fun extractFunctionName(tokenText: String): String {
        // Remove scope prefix and opening parenthesis
        // e.g., "event:year(" -> "year"
        return tokenText.substringAfterLast(":").removeSuffix("(")
    }

    private fun translateScalarFunction0(funcName: String): String =
        when (funcName.lowercase()) {
            "now" -> "datetime()" // Neo4j equivalent
            else -> throw IllegalArgumentException("Unsupported scalar function: $funcName")
        }

    private fun translateScalarFunction1(
        funcName: String,
        arg: String,
    ): String =
        when (funcName.lowercase()) {
            // Date/time extraction
            "year" -> "date($arg).year"
            "month" -> "date($arg).month"
            "day" -> "date($arg).day"
            "hour" -> "time($arg).hour"
            "minute" -> "time($arg).minute"
            "second" -> "time($arg).second"
            "millisecond" -> "time($arg).millisecond"
            "quarter" -> "((date($arg).month - 1) / 3) + 1" // Calculate quarter
            "dayofweek" -> "date($arg).dayOfWeek"

            // String manipulation
            "upper" -> "toUpper($arg)"
            "lower" -> "toLower($arg)"

            // Math
            "round" -> "round($arg)"

            // Date/time parsing
            "date" -> "date($arg)"
            "time" -> "time($arg)"

            else -> throw IllegalArgumentException("Unsupported scalar function: $funcName")
        }

    private fun translateAggregateFunction(
        funcName: String,
        arg: String,
    ): String =
        when (funcName.lowercase()) {
            "count" -> "count($arg)"
            "sum" -> "sum($arg)"
            "avg" -> "avg($arg)"
            "min" -> "min($arg)"
            "max" -> "max($arg)"
            else -> throw IllegalArgumentException("Unsupported aggregate function: $funcName")
        }

    // ========================================
    // SCALARS & IDENTIFIERS
    // ========================================

    /**
     * scalar: STRING | NUMBER | BOOLEAN | DATETIME | UUID | NULL
     */
    override fun visitScalar(ctx: QLParser.ScalarContext): Any? =
        when {
            ctx.STRING() != null -> {
                var value = removeQuotes(ctx.STRING().text)
                // Handle dates in string format: 'D2006-01-01' -> '2006-01-01'
                if (value.startsWith("D") && value.length >= 10 &&
                    value[1].isDigit() && value[5] == '-' && value[8] == '-'
                ) {
                    value = value.substring(1) // Remove 'D' prefix
                }
                value
            }

            ctx.NUMBER() != null -> {
                val text = ctx.NUMBER().text
                if (text.contains(".")) text.toDouble() else text.toLong()
            }

            ctx.BOOLEAN() != null -> ctx.BOOLEAN().text.toBoolean()
            ctx.DATETIME() != null -> {
                // Remove scope prefix and 'D' prefix from datetime
                // Examples: "D2006-01-01" -> "2006-01-01", "event:D2006-01-01T12:00:00" -> "2006-01-01T12:00:00"
                var datetime = ctx.DATETIME().text
                // Remove scope prefix if present (log:, trace:, event:, etc.)
                if (datetime.contains(":")) {
                    datetime = datetime.substringAfter(":")
                }
                // Remove 'D' prefix
                if (datetime.startsWith("D")) {
                    datetime = datetime.substring(1)
                }
                datetime
            }

            ctx.UUID() != null -> ctx.UUID().text
            ctx.NULL() != null -> null
            else -> throw IllegalStateException("Unknown scalar type")
        }

    /**
     * Translate field reference with scope prefix and hoisting support
     *
     * Examples:
     * - event:activity → event.activity
     * - e:name → event.activity (shorthand mapping)
     * - e:group → event.org_group (shorthand mapping)
     * - ^e:name → trace.concept_name (hoisting: event → trace)
     * - ^^e:name → log.concept_name (double hoisting: event → log)
     * - activity → event.activity (no scope, uses current scope)
     */
    private fun translateFieldReference(fieldRef: String): String {
        // Remove brackets if present: [event:activity] → event:activity
        val cleanRef = fieldRef.trim('[', ']')

        // Extract hoisting prefix (^, ^^, etc.)
        val hoistingPrefix = cleanRef.takeWhile { it == '^' }
        val refWithoutHoisting = cleanRef.drop(hoistingPrefix.length)

        // Check if has scope prefix
        if (refWithoutHoisting.contains(":")) {
            val parts = refWithoutHoisting.split(":", limit = 2)
            val scopePart = parts[0]
            val fieldPart = parts[1]

            // Parse base scope
            val baseScope =
                try {
                    Scope.parse(scopePart)
                } catch (e: IllegalArgumentException) {
                    // Not a valid scope prefix - treat as field name
                    return translateField(cleanRef, scopeToNodeLabel(currentScope))
                }

            // Apply hoisting
            val effectiveScope =
                if (hoistingPrefix.isNotEmpty()) {
                    StandardAttributeMapper.applyHoisting(baseScope, hoistingPrefix)
                } else {
                    baseScope
                }

            // Track that this scope is used in the query
            usedScopes.add(effectiveScope)

            // Translate to Neo4j property
            val neo4jProperty = StandardAttributeMapper.translateToNeo4jProperty(fieldPart, effectiveScope)
            val nodeLabel = scopeToNodeLabel(effectiveScope)

            return "$nodeLabel.$neo4jProperty"
        } else {
            // No scope prefix - use current scope
            val effectiveScope =
                if (hoistingPrefix.isNotEmpty()) {
                    StandardAttributeMapper.applyHoisting(currentScope, hoistingPrefix)
                } else {
                    currentScope
                }

            // Track that this scope is used in the query
            usedScopes.add(effectiveScope)

            val neo4jProperty = StandardAttributeMapper.translateToNeo4jProperty(refWithoutHoisting, effectiveScope)
            val nodeLabel = scopeToNodeLabel(effectiveScope)

            return "$nodeLabel.$neo4jProperty"
        }
    }

    private fun scopeToNodeLabel(scope: Scope): String =
        when (scope) {
            Scope.Log -> "log"
            Scope.Trace -> "trace"
            Scope.Event -> "event"
        }

    /**
     * Legacy translateField - now delegates to StandardAttributeMapper
     * Kept for backward compatibility
     */
    private fun translateField(
        field: String,
        nodeLabel: String,
    ): String {
        // Determine scope from nodeLabel
        val scope =
            when (nodeLabel) {
                "log" -> Scope.Log
                "trace" -> Scope.Trace
                "event" -> Scope.Event
                else -> Scope.Event
            }

        val neo4jProperty = StandardAttributeMapper.translateToNeo4jProperty(field, scope)
        return "$nodeLabel.$neo4jProperty"
    }

    // ========================================
    // OTHER CLAUSES
    // ========================================

    /**
     * group_by: GROUP_BY id_list
     */
    override fun visitGroup_by(ctx: QLParser.Group_byContext): List<String> = visitId_list(ctx.id_list()) as List<String>

    /**
     * id_list: ID (',' ID)*
     */
    override fun visitId_list(ctx: QLParser.Id_listContext): List<String> = ctx.ID().map { translateFieldReference(it.text) }

    /**
     * order_by: ORDER_BY column_list_with_order
     */
    override fun visitOrder_by(ctx: QLParser.Order_byContext): List<OrderByItem> =
        visitColumn_list_with_order(ctx.column_list_with_order()) as List<OrderByItem>

    /**
     * column_list_with_order: ordered_expression_root (',' ordered_expression_root)*
     */
    override fun visitColumn_list_with_order(ctx: QLParser.Column_list_with_orderContext): List<OrderByItem> =
        ctx.ordered_expression_root().map {
            visitOrdered_expression_root(it) as OrderByItem
        }

    /**
     * ordered_expression_root: arith_expr order_dir
     */
    override fun visitOrdered_expression_root(ctx: QLParser.Ordered_expression_rootContext): OrderByItem {
        val expr = visitArith_expr(ctx.arith_expr()) as String
        val direction = visitOrder_dir(ctx.order_dir()) as String
        return OrderByItem(expr, direction)
    }

    /**
     * order_dir: (empty) | ORDER_ASC | ORDER_DESC
     */
    override fun visitOrder_dir(ctx: QLParser.Order_dirContext): String =
        when {
            ctx.ORDER_ASC() != null -> "ASC"
            ctx.ORDER_DESC() != null -> "DESC"
            else -> "ASC" // Default
        }

    /**
     * limit: LIMIT limit_number (',' limit_number)*
     */
    override fun visitLimit(ctx: QLParser.LimitContext): List<Int> = ctx.limit_number().map { visitLimit_number(it) as Int }

    override fun visitLimit_number(ctx: QLParser.Limit_numberContext): Int = ctx.NUMBER().text.toInt()

    // ========================================
    // QUERY OBJECT TO CYPHER TRANSLATION
    // ========================================

    /**
     * Translate a Query object to Cypher.
     *
     * This is the new entry point that works with the Query model instead of
     * directly visiting the parse tree.
     */
    private fun translateQueryToCypher(query: Query): CypherQuery {
        // Clear state
        usedScopes.clear()
        parameters.clear()
        paramCounter = 0

        // Determine if this is SELECT or DELETE
        return if (query.deleteScope != null) {
            translateDeleteQuery(query)
        } else {
            translateSelectQuery(query)
        }
    }

    /**
     * Translate SELECT query from Query object to Cypher.
     */
    private fun translateSelectQuery(query: Query): CypherQuery {
        val hierarchicalLimits = mutableMapOf<String, Int?>()
        val hierarchicalOffsets = mutableMapOf<String, Int?>()

        query.limit[com.processm.processminterpreter.pql.model.Scope.Log]?.let {
            hierarchicalLimits["log"] = it.toInt()
        }
        query.limit[com.processm.processminterpreter.pql.model.Scope.Trace]?.let {
            hierarchicalLimits["trace"] = it.toInt()
        }
        query.limit[com.processm.processminterpreter.pql.model.Scope.Event]?.let {
            hierarchicalLimits["event"] = it.toInt()
        }

        // Extract hierarchical offsets
        query.offset[com.processm.processminterpreter.pql.model.Scope.Log]?.let {
            hierarchicalOffsets["log"] = it.toInt()
        }
        query.offset[com.processm.processminterpreter.pql.model.Scope.Trace]?.let {
            hierarchicalOffsets["trace"] = it.toInt()
        }
        query.offset[com.processm.processminterpreter.pql.model.Scope.Event]?.let {
            hierarchicalOffsets["event"] = it.toInt()
        }

        logger.debug("Query.limit map: {}", query.limit)
        logger.debug("Query.offset map: {}", query.offset)
        logger.debug("Extracted hierarchicalLimits: {}", hierarchicalLimits)
        logger.debug("Extracted hierarchicalOffsets: {}", hierarchicalOffsets)

        // Apply default trace limit if no explicit trace limit is set
        if (defaultTraceLimit != null && !hierarchicalLimits.containsKey("trace")) {
            hierarchicalLimits["trace"] = defaultTraceLimit
        }

        // Use hierarchical query structure with COLLECT/UNWIND for 100% ProcessM compatibility
        if (hierarchicalLimits.isNotEmpty() || hierarchicalOffsets.isNotEmpty()) {
            return buildHierarchicalQueryWithLimits(query, hierarchicalLimits, hierarchicalOffsets)
        }

        // Fallback to old approach for queries without LIMIT
        val cypher = StringBuilder()

        // Determine primary scope (scope with lowest ordinal = highest priority)
        val primaryScope = determinePrimaryScope(query)
        val mappedScope = mapScope(primaryScope)
        currentScope = mappedScope

        // Populate usedScopes from Query object to ensure MATCH clause is correct
        populateUsedScopes(query)

        // Build MATCH clause
        cypher.append(buildMatchClause(mappedScope))

        // Build WHERE clause
        val whereClause = buildWhereClauseFromQuery(query)
        if (whereClause != null || logId != null) {
            cypher.append(" WHERE ")
            val conditions = mutableListOf<String>()

            if (logId != null) {
                conditions.add("log.logId = \$logId")
                parameters["logId"] = logId
            }

            if (whereClause != null) {
                conditions.add(whereClause)
            }

            cypher.append(conditions.joinToString(" AND "))
        }

        // Build RETURN clause
        cypher.append(" RETURN ")
        val returnClause = buildReturnClauseFromQuery(query)
        cypher.append(returnClause)

        // Build ORDER BY clause
        val orderByClause = buildOrderByClauseFromQuery(query)
        val hasExplicitEventOrderBy = query.orderByExpressions[com.processm.processminterpreter.pql.model.Scope.Event]?.isNotEmpty() == true
        // Don't add default ORDER BY when query has aggregation (Neo4j prohibits referencing
        // non-aggregated variables after RETURN with aggregation)
        val hasAggregation = query.selectExpressions.values.flatten().any { expr ->
            expr is com.processm.processminterpreter.pql.model.Function &&
                com.processm.processminterpreter.pql.model.Function.isAggregation(expr.name)
        }

        if (orderByClause != null && orderByClause.isNotEmpty()) {
            cypher.append(" ORDER BY ")
            cypher.append(orderByClause.joinToString(", ") { "${it.expression} ${it.direction}" })
            // Add default event ordering as tiebreaker if not explicitly specified
            if (!hasExplicitEventOrderBy && !hasAggregation && usedScopes.contains(Scope.Event)) {
                cypher.append(", event.timestamp ASC, event.activity ASC, event.lifecycle ASC, event.resource ASC")
            }
        } else if (usedScopes.contains(Scope.Event) && !hasAggregation) {
            // No explicit ORDER BY - add default event ordering for ProcessM compatibility
            cypher.append(" ORDER BY event.timestamp ASC, event.activity ASC, event.lifecycle ASC, event.resource ASC")
        }

        // Build SKIP (OFFSET) clause
        val offset = query.offset[primaryScope]
            ?: query.offset[com.processm.processminterpreter.pql.model.Scope.Event]
            ?: query.offset.values.firstOrNull()

        if (offset != null) {
            cypher.append(" SKIP $offset")
        }

        return CypherQuery(cypher.toString(), parameters.toMap(), emptyMap())
    }

    /**
     * Build hierarchical query using COLLECT/UNWIND for ProcessM-compatible LIMIT/OFFSET behavior.
     *
     * This ensures limits and offsets are applied hierarchically:
     * - limit l:1, t:2, e:3 = 1 log with max 2 traces, each trace with max 3 events
     * - offset l:1, t:2, e:3 = skip 1 log, skip 2 traces per log, skip 3 events per trace
     *
     * Uses COLLECT to limit at each level, then UNWIND to continue processing.
     * WHERE conditions are applied at the appropriate scope level.
     *
     * List slicing: collect(x)[offset..offset+limit] or collect(x)[offset..] if no limit
     */
    private fun buildHierarchicalQueryWithLimits(
        query: Query,
        hierarchicalLimits: Map<String, Int?>,
        hierarchicalOffsets: Map<String, Int?> = emptyMap()
    ): CypherQuery {
        val cypher = StringBuilder()

        val primaryScope = determinePrimaryScope(query)
        val mappedScope = mapScope(primaryScope)
        currentScope = mappedScope

        populateUsedScopes(query)

        // Ensure log/trace nodes are matched when hierarchical limits reference them,
        // even if no log/trace attributes are explicitly selected
        val hasTraceLimit = hierarchicalLimits.containsKey("trace") || defaultTraceLimit != null
        val needsLog = usedScopes.contains(Scope.Log) || logId != null ||
            hierarchicalLimits.containsKey("log") || hasTraceLimit
        val needsTrace = usedScopes.contains(Scope.Trace) || hasTraceLimit
        val needsEvent = usedScopes.contains(Scope.Event)

        val logLimit = hierarchicalLimits["log"]
        val traceLimit = hierarchicalLimits["trace"] ?: defaultTraceLimit
        val eventLimit = hierarchicalLimits["event"]

        val logOffset = hierarchicalOffsets["log"] ?: 0
        val traceOffset = hierarchicalOffsets["trace"] ?: 0
        val eventOffset = hierarchicalOffsets["event"] ?: 0

        // Separate WHERE conditions by scope
        val logConditions = mutableListOf<String>()
        val traceConditions = mutableListOf<String>()
        val eventConditions = mutableListOf<String>()

        if (logId != null) {
            logConditions.add("log.logId = \$logId")
            parameters["logId"] = logId
        }

        // Build scoped WHERE conditions from query
        buildScopedWhereConditions(query, logConditions, traceConditions, eventConditions)

        // Step 1: MATCH logs
        if (needsLog) {
            if (logId != null) {
                cypher.append("MATCH (log:Log {logId: \$logId})")
            } else {
                cypher.append("MATCH (log:Log)")
            }

            // Apply log-level WHERE conditions only
            if (logConditions.isNotEmpty()) {
                cypher.append(" WHERE ").append(logConditions.joinToString(" AND "))
            }

            // Apply log LIMIT/OFFSET using COLLECT with deterministic ordering (by insertion order)
            // ProcessM behavior: LIMIT first, then OFFSET from the limited set
            // limit l:10 offset l:2 = first 10, skip first 2 = 8 results (indices 2-9)
            if (logLimit != null || logOffset > 0) {
                cypher.append(" WITH log ORDER BY log.createdAt")
                val endIndex = logLimit // End at limit (not offset+limit)
                val sliceExpr = if (endIndex != null) "[$logOffset..$endIndex]" else "[$logOffset..]"
                cypher.append(" WITH collect(log)$sliceExpr as logs")
                cypher.append(" UNWIND logs as log")
            }
        }

        // Step 2: MATCH traces
        if (needsTrace || needsEvent) {
            cypher.append(" MATCH (log)-[:CONTAINS]->(trace:Trace)")

            // Apply trace-level WHERE conditions
            if (traceConditions.isNotEmpty()) {
                cypher.append(" WHERE ").append(traceConditions.joinToString(" AND "))
            }

            // Apply trace LIMIT/OFFSET using COLLECT with deterministic ordering (by insertion order)
            // ProcessM behavior: LIMIT first, then OFFSET from the limited set
            if (traceLimit != null || traceOffset > 0) {
                cypher.append(" WITH log, trace ORDER BY log.createdAt, trace.createdAt")
                val endIndex = traceLimit // End at limit (not offset+limit)
                val sliceExpr = if (endIndex != null) "[$traceOffset..$endIndex]" else "[$traceOffset..]"
                cypher.append(" WITH log, collect(trace)$sliceExpr as traces")
                cypher.append(" UNWIND traces as trace")
            } else if (eventLimit == null || eventLimit == 0) {
                // Only add WITH if we don't have an event limit to apply
                // This avoids interfering with subsequent event collection grouping
                cypher.append(" WITH log, trace")
            }
            // else: no WITH needed, we'll go straight to matching events and collect there
        }

        // Step 3: MATCH events
        if (needsEvent) {
            if (eventLimit == 0) {
                // For limit e:0, we don't need to MATCH events at all
                // Just continue with log and trace - no event in RETURN will return NULL for event fields
                // This is ProcessM-compatible: traces without events
            } else {
                // Normal case: MATCH events
                cypher.append(" MATCH (trace)-[:HAS_EVENT]->(event:Event)")

                // Apply event-level WHERE conditions
                if (eventConditions.isNotEmpty()) {
                    cypher.append(" WHERE ").append(eventConditions.joinToString(" AND "))
                }

                // Apply event LIMIT/OFFSET using COLLECT with timestamp ordering (ProcessM compatibility)
                // ProcessM behavior: LIMIT first, then OFFSET from the limited set
                if (eventLimit != null || eventOffset > 0) {
                    cypher.append(" WITH log, trace, event ORDER BY log.createdAt, trace.createdAt, event.timestamp, event.activity, event.lifecycle, event.resource")
                    val endIndex = eventLimit // End at limit (not offset+limit)
                    val sliceExpr = if (endIndex != null) "[$eventOffset..$endIndex]" else "[$eventOffset..]"
                    cypher.append(" WITH log, trace, collect(event)$sliceExpr as events")
                    cypher.append(" UNWIND events as event")
                }
            }
        }

        // Build RETURN clause - exclude event if eventLimit == 0
        cypher.append(" RETURN ")
        val returnClause = buildReturnClauseFromQuery(query, eventLimit)
        cypher.append(returnClause)

        // Build ORDER BY clause
        val orderByClause = buildOrderByClauseFromQuery(query)
        val hasExplicitEventOrderBy = query.orderByExpressions[com.processm.processminterpreter.pql.model.Scope.Event]?.isNotEmpty() == true
        val hasAggregationH = query.selectExpressions.values.flatten().any { expr ->
            expr is com.processm.processminterpreter.pql.model.Function &&
                com.processm.processminterpreter.pql.model.Function.isAggregation(expr.name)
        }

        if (orderByClause != null && orderByClause.isNotEmpty()) {
            cypher.append(" ORDER BY ")
            cypher.append(orderByClause.joinToString(", ") { "${it.expression} ${it.direction}" })
            // Add default event ordering as tiebreaker if not explicitly specified
            if (!hasExplicitEventOrderBy && !hasAggregationH && needsEvent && eventLimit != 0) {
                cypher.append(", event.timestamp ASC, event.activity ASC, event.lifecycle ASC, event.resource ASC")
            }
        } else if (needsEvent && eventLimit != 0 && !hasAggregationH) {
            // No explicit ORDER BY - add default event ordering for ProcessM compatibility
            cypher.append(" ORDER BY event.timestamp ASC, event.activity ASC, event.lifecycle ASC, event.resource ASC")
        }

        // Note: No need to pass hierarchicalLimits to HierarchyReconstructor
        // because limits are already applied in Cypher
        val generatedCypher = cypher.toString()
        logger.debug("Generated hierarchical Cypher: $generatedCypher")
        return CypherQuery(generatedCypher, parameters.toMap(), hierarchicalLimits)
    }

    /**
     * Translate DELETE query from Query object to Cypher.
     */
    private fun translateDeleteQuery(query: Query): CypherQuery {
        val cypher = StringBuilder()

        val deleteScope = query.deleteScope ?: throw IllegalStateException("DELETE query must have deleteScope")
        val mappedScope = mapScope(deleteScope)
        currentScope = mappedScope

        // Build MATCH clause
        cypher.append(buildMatchClause(mappedScope))

        // Build WHERE clause
        val whereClause = buildWhereClauseFromQuery(query)
        if (whereClause != null || logId != null) {
            cypher.append(" WHERE ")
            val conditions = mutableListOf<String>()

            if (logId != null) {
                conditions.add("log.logId = \$logId")
                parameters["logId"] = logId
            }

            if (whereClause != null) {
                conditions.add(whereClause)
            }

            cypher.append(conditions.joinToString(" AND "))
        }

        // For DELETE with LIMIT/ORDER, we need to collect IDs first
        val orderByClause = buildOrderByClauseFromQuery(query)
        
        // Robust lookup: Primary Scope -> EVENT Scope -> Any Scope
        val limit = query.limit[deleteScope] 
            ?: query.limit[com.processm.processminterpreter.pql.model.Scope.Event]
            ?: query.limit.values.firstOrNull()
            
        val offset = query.offset[deleteScope]
            ?: query.offset[com.processm.processminterpreter.pql.model.Scope.Event]
            ?: query.offset.values.firstOrNull()

        if (limit != null || offset != null || orderByClause != null) {
            val nodeLabel = scopeToNodeLabel(mappedScope)
            cypher.append(" WITH $nodeLabel")

            if (orderByClause != null && orderByClause.isNotEmpty()) {
                cypher.append(" ORDER BY ")
                cypher.append(orderByClause.joinToString(", ") { "${it.expression} ${it.direction}" })
            }

            if (offset != null) {
                cypher.append(" SKIP $offset")
            }

            if (limit != null) {
                cypher.append(" LIMIT $limit")
            }
        }

        // DETACH DELETE to remove relationships too
        val nodeLabel = scopeToNodeLabel(mappedScope)
        cypher.append(" DETACH DELETE $nodeLabel")

        return CypherQuery(cypher.toString(), parameters.toMap())
    }

    /**
     * Map from model.Scope to StandardAttributeMapper.Scope
     */
    private fun mapScope(modelScope: com.processm.processminterpreter.pql.model.Scope): Scope =
        when (modelScope) {
            com.processm.processminterpreter.pql.model.Scope.Log -> Scope.Log
            com.processm.processminterpreter.pql.model.Scope.Trace -> Scope.Trace
            com.processm.processminterpreter.pql.model.Scope.Event -> Scope.Event
        }

    /**
     * Determine the primary scope from a Query object.
     *
     * Rules:
     * 1. If DELETE, use deleteScope
     * 2. If SELECT with explicit attributes/expressions, find minimum scope (LOG < TRACE < EVENT)
     * 3. Default to EVENT
     */
    private fun determinePrimaryScope(query: Query): com.processm.processminterpreter.pql.model.Scope {
        // DELETE query
        query.deleteScope?.let { return it }

        // SELECT with attributes - find minimum scope (highest in hierarchy)
        val scopes = mutableSetOf<com.processm.processminterpreter.pql.model.Scope>()

        // Add scopes from SELECT attributes
        query.selectStandardAttributes.forEach { (scope, attrs) -> if (attrs.isNotEmpty()) scopes.add(scope) }
        query.selectOtherAttributes.forEach { (scope, attrs) -> if (attrs.isNotEmpty()) scopes.add(scope) }
        query.selectExpressions.forEach { (scope, exprs) -> if (exprs.isNotEmpty()) scopes.add(scope) }

        // Add scopes from selectAll
        query.selectAll.forEach { (scope, isAll) ->
            if (isAll == true) scopes.add(scope)
        }

        // Return minimum scope (LOG = 0 < TRACE = 1 < EVENT = 2)
        return scopes.minByOrNull { it.ordinal } ?: com.processm.processminterpreter.pql.model.Scope.Event
    }

    /**
     * Build WHERE clause from Query object.
     */
    private fun buildWhereClauseFromQuery(query: Query): String? {
        if (query.whereExpression == com.processm.processminterpreter.pql.model.Expression.empty) {
            return null
        }
        return translateExpressionToCypher(query.whereExpression)
    }

    /**
     * Build scoped WHERE conditions from Query object.
     *
     * Separates WHERE conditions by the scope of attributes they reference.
     * This is necessary for hierarchical queries where we MATCH at different levels.
     *
     * Rules:
     * - Conditions referencing only LOG attributes go to logConditions
     * - Conditions referencing TRACE (but not EVENT) go to traceConditions
     * - Conditions referencing EVENT go to eventConditions
     * - AND conditions are split if possible (left to log, right to event, etc.)
     * - OR conditions must be kept together at the lowest (most specific) scope
     */
    private fun buildScopedWhereConditions(
        query: Query,
        logConditions: MutableList<String>,
        traceConditions: MutableList<String>,
        eventConditions: MutableList<String>
    ) {
        if (query.whereExpression == com.processm.processminterpreter.pql.model.Expression.empty) {
            return
        }

        // Process the WHERE expression tree
        processWhereExpression(query.whereExpression, logConditions, traceConditions, eventConditions)
    }

    /**
     * Process a WHERE expression and add it to the appropriate scope list.
     */
    private fun processWhereExpression(
        expr: com.processm.processminterpreter.pql.model.IExpression,
        logConditions: MutableList<String>,
        traceConditions: MutableList<String>,
        eventConditions: MutableList<String>
    ) {
        when (expr) {
            is BinaryOperator -> {
                val operator = expr.operator.uppercase()
                if (operator == "AND") {
                    // AND conditions can be split - process each side separately
                    processWhereExpression(expr.left, logConditions, traceConditions, eventConditions)
                    processWhereExpression(expr.right, logConditions, traceConditions, eventConditions)
                } else {
                    // OR and other operators - keep together, determine scope from effective scope
                    val scope = determineExpressionScope(expr)
                    val condition = translateExpressionToCypher(expr)
                    addConditionToScope(scope, condition, logConditions, traceConditions, eventConditions)
                }
            }
            else -> {
                // For non-binary expressions, determine scope and add to appropriate list
                val scope = determineExpressionScope(expr)
                val condition = translateExpressionToCypher(expr)
                addConditionToScope(scope, condition, logConditions, traceConditions, eventConditions)
            }
        }
    }

    /**
     * Determine the scope of an expression based on the attributes it references.
     *
     * Returns the lowest (most specific) scope used in the expression.
     * LOG < TRACE < EVENT (EVENT is lowest/most specific)
     */
    private fun determineExpressionScope(expr: com.processm.processminterpreter.pql.model.IExpression): com.processm.processminterpreter.pql.model.Scope {
        val scopes = mutableSetOf<com.processm.processminterpreter.pql.model.Scope>()
        collectExpressionScopes(expr, scopes)

        // Return the lowest scope (highest ordinal = most specific)
        // Default to LOG if no scopes found (e.g., for literal comparisons like "where 0=1")
        return scopes.maxByOrNull { it.ordinal } ?: com.processm.processminterpreter.pql.model.Scope.Log
    }

    /**
     * Collect all scopes referenced in an expression.
     */
    private fun collectExpressionScopes(
        expr: com.processm.processminterpreter.pql.model.IExpression,
        scopes: MutableSet<com.processm.processminterpreter.pql.model.Scope>
    ) {
        when (expr) {
            is com.processm.processminterpreter.pql.model.Attribute -> {
                // Use effectiveScope which accounts for hoisting
                val scope = expr.effectiveScope ?: com.processm.processminterpreter.pql.model.Scope.Event
                scopes.add(scope)
            }
            is com.processm.processminterpreter.pql.model.Function -> {
                expr.children.forEach { collectExpressionScopes(it, scopes) }
            }
            is BinaryOperator -> {
                collectExpressionScopes(expr.left, scopes)
                collectExpressionScopes(expr.right, scopes)
            }
            is UnaryOperator -> {
                collectExpressionScopes(expr.operand, scopes)
            }
            is InListExpression -> {
                // InListExpression values are literals, no scope
            }
            // Literals have no scope
            else -> {}
        }
    }

    /**
     * Add a condition to the appropriate scope list.
     */
    private fun addConditionToScope(
        scope: com.processm.processminterpreter.pql.model.Scope,
        condition: String,
        logConditions: MutableList<String>,
        traceConditions: MutableList<String>,
        eventConditions: MutableList<String>
    ) {
        when (scope) {
            com.processm.processminterpreter.pql.model.Scope.Log -> logConditions.add(condition)
            com.processm.processminterpreter.pql.model.Scope.Trace -> traceConditions.add(condition)
            com.processm.processminterpreter.pql.model.Scope.Event -> eventConditions.add(condition)
        }
    }

    /**
     * Translate an IExpression to Cypher string.
     *
     * This is the core expression translator that handles:
     * - Binary operators (=, >, <, AND, OR, IN, LIKE, etc.)
     * - Unary operators (NOT, IS NULL)
     * - Attributes (map to Cypher fields)
     * - Literals (strings, numbers, dates, booleans, null)
     * - Functions (aggregations and scalar functions)
     * - InListExpression
     */
    private fun translateExpressionToCypher(expr: com.processm.processminterpreter.pql.model.IExpression): String =
        when (expr) {
            is BinaryOperator -> translateBinaryOperator(expr)
            is UnaryOperator -> translateUnaryOperator(expr)
            is InListExpression -> translateInListExpression(expr)
            is com.processm.processminterpreter.pql.model.Attribute -> translateAttribute(expr)
            is com.processm.processminterpreter.pql.model.Function -> translateFunction(expr)
            is com.processm.processminterpreter.pql.model.StringLiteral -> translateStringLiteral(expr)
            is com.processm.processminterpreter.pql.model.NumberLiteral -> translateNumberLiteral(expr)
            is com.processm.processminterpreter.pql.model.DateTimeLiteral -> translateDateTimeLiteral(expr)
            is com.processm.processminterpreter.pql.model.BooleanLiteral -> translateBooleanLiteral(expr)
            is com.processm.processminterpreter.pql.model.NullLiteral -> "null"
            else -> throw IllegalArgumentException("Unknown expression type: ${expr::class.simpleName}")
        }

    /**
     * Translate BinaryOperator to Cypher.
     */
    private fun translateBinaryOperator(op: BinaryOperator): String {
        val left = translateExpressionToCypher(op.left)
        val right = translateExpressionToCypher(op.right)
        val operator = op.operator.uppercase()

        return when (operator) {
            "=", "<>", "!=", ">", ">=", "<", "<=", "AND", "OR" -> "($left $operator $right)"
            "IN" -> "$left IN $right"
            "NOT IN" -> "NOT ($left IN $right)" // Cypher doesn't have NOT IN, use NOT (... IN ...)
            "LIKE" -> {
                // LIKE with SQL wildcards (%, _) -> convert to Cypher regex
                // % -> .*
                // _ -> .
                // For now, use =~ with the pattern, assuming the right side is already a regex pattern
                // If it's a simple LIKE, user may need to adjust pattern
                "$left =~ $right"
            }
            "MATCHES" -> "$left =~ $right"
            "+" -> "($left + $right)"
            "-" -> "($left - $right)"
            "*" -> "($left * $right)"
            "/" -> "($left / $right)"
            "%" -> "($left % $right)"
            else -> "($left $operator $right)"
        }
    }

    /**
     * Translate UnaryOperator to Cypher.
     */
    private fun translateUnaryOperator(op: UnaryOperator): String {
        val operand = translateExpressionToCypher(op.operand)
        val operator = op.operator.uppercase()

        return when (operator) {
            "NOT" -> "NOT ($operand)"
            "IS NULL" -> "$operand IS NULL"
            "IS NOT NULL" -> "$operand IS NOT NULL"
            "-" -> "-$operand"
            else -> "$operator $operand"
        }
    }

    /**
     * Translate InListExpression to Cypher array literal.
     * For IN lists, we store the entire list as a single parameter.
     */
    private fun translateInListExpression(expr: InListExpression): String {
        // Extract raw values from the list (strings, numbers, etc.)
        val rawValues =
            expr.values.map { value ->
                when (value) {
                    is com.processm.processminterpreter.pql.model.StringLiteral -> value.value
                    is com.processm.processminterpreter.pql.model.NumberLiteral -> value.value
                    is com.processm.processminterpreter.pql.model.DateTimeLiteral -> {
                        // Convert LocalDateTime to ISO string
                        // If time is midnight, format as date-only
                        if (value.value.hour == 0 && value.value.minute == 0 && value.value.second == 0) {
                            value.value.toLocalDate().toString()
                        } else {
                            value.value.toString()
                        }
                    }

                    is com.processm.processminterpreter.pql.model.BooleanLiteral -> value.value
                    is com.processm.processminterpreter.pql.model.NullLiteral -> null
                    else -> throw IllegalArgumentException("Unsupported value type in IN list: ${value::class.simpleName}")
                }
            }

        // Store the entire list as a single parameter
        val paramName = "param${paramCounter++}"
        parameters[paramName] = rawValues
        return "\$$paramName"
    }

    /**
     * Translate Attribute to Cypher field reference.
     */
    private fun translateAttribute(attr: com.processm.processminterpreter.pql.model.Attribute): String {
        // Use effectiveScope to handle hoisting correctly (e.g. ^e:caseId -> trace.caseId)
        val scope = mapScope(attr.effectiveScope ?: com.processm.processminterpreter.pql.model.Scope.Event)
        val nodeLabel = scopeToNodeLabel(scope)
        return attributeToCypherField(attr, nodeLabel, scope)
    }



    /**
     * Translate Function to Cypher function call.
     */
    private fun translateFunction(func: com.processm.processminterpreter.pql.model.Function): String {
        val funcName = func.name.lowercase()
        val args = func.children.map { translateExpressionToCypher(it) }

        // Handle date/time extraction functions which should be property accessors in Cypher
        // e.g. year(date) -> date.year
        val dateProperty = when (funcName) {
            "year" -> "year"
            "month" -> "month"
            "day" -> "day"
            "hour" -> "hour"
            "minute" -> "minute"
            "second" -> "second"
            "dayofweek" -> "dayOfWeek"
            else -> null
        }

        if (dateProperty != null && args.size == 1) {
            // If argument is a property (e.g. event.timestamp), append .property
            // If argument is a complex expression, wrap in parentheses?
            // For now, we assume simple usage.
            // We also need to ensure the argument is treated as a date/datetime.
            // If it's a string property, we might need date(arg).year
            // But if it's already a datetime property, arg.year works.
            // Given we don't know the type at translation time easily, we'll assume it's a temporal type
            // OR we wrap it in date() or datetime() if it's not?
            // ProcessM usually treats timestamp as string in XES, but Neo4j import might convert it.
            // Let's try direct property access first: arg.year
            return "${args[0]}.$dateProperty"
        }

        // Map PQL function names to Cypher/Neo4j function names for other functions
        val cypherFuncName =
            when (funcName) {
                // Aggregation functions
                "count" -> {
                    if (args.isNotEmpty()) {
                        val arg = args[0]
                        if (arg.endsWith(".traceId") || arg.endsWith(".logId") || arg.endsWith(".eventId")) {
                            return "count(DISTINCT $arg)"
                        }
                    }
                    "count"
                }
                "sum", "avg", "min", "max" -> funcName

                // Scalar functions - date/time (constructors)
                "now" -> "datetime" // datetime()

                // String functions
                "lower", "upper", "trim" -> funcName
                "substring" -> "substring"
                "length" -> "size"

                // Math functions
                "abs", "ceil", "floor", "round", "sqrt" -> funcName

                // Default: use as-is
                else -> funcName
            }

        return if (args.isEmpty()) {
            "$cypherFuncName()"
        } else {
            "$cypherFuncName(${args.joinToString(", ")})"
        }
    }

    /**
     * Translate StringLiteral to Cypher string.
     */
    private fun translateStringLiteral(lit: com.processm.processminterpreter.pql.model.StringLiteral): String {
        // Use parameterized queries to avoid SQL injection
        val paramName = "param${paramCounter++}"
        // Handle dates in string format: 'D2005-01-01' -> '2005-01-01'
        val value =
            if (lit.value.startsWith("D") && lit.value.length >= 10 &&
                lit.value[1].isDigit() && lit.value[5] == '-' && lit.value[8] == '-'
            ) {
                lit.value.substring(1) // Remove 'D' prefix from date strings
            } else {
                lit.value
            }
        parameters[paramName] = value
        return "\$$paramName"
    }

    /**
     * Translate NumberLiteral to Cypher number.
     */
    private fun translateNumberLiteral(lit: com.processm.processminterpreter.pql.model.NumberLiteral): String = lit.value.toString()

    /**
     * Translate DateTimeLiteral to Cypher datetime.
     */
    private fun translateDateTimeLiteral(lit: com.processm.processminterpreter.pql.model.DateTimeLiteral): String {
        // Use parameterized query
        val paramName = "param${paramCounter++}"
        // Convert LocalDateTime to ISO string
        // If time is midnight (00:00:00), format as date-only, otherwise include time
        val dateValue =
            if (lit.value.hour == 0 && lit.value.minute == 0 && lit.value.second == 0) {
                lit.value.toLocalDate().toString() // Date-only format: 2005-01-01
            } else {
                lit.value.toString() // Full datetime format: 2005-01-01T12:30:00
            }
        parameters[paramName] = lit.value.toString()
        return "datetime(\$$paramName)"
    }

    /**
     * Translate BooleanLiteral to Cypher boolean.
     */
    private fun translateBooleanLiteral(lit: com.processm.processminterpreter.pql.model.BooleanLiteral): String = lit.value.toString()

    /**
     * Build RETURN clause from Query object.
     * Iterates through all scopes that have SELECT attributes and includes them in the RETURN.
     */
    private fun buildReturnClauseFromQuery(query: Query, eventLimit: Int? = null): String {
        val allParts = mutableListOf<String>()

        // Collect all scopes that have SELECT attributes (only non-empty ones)
        val scopesWithSelects = mutableSetOf<com.processm.processminterpreter.pql.model.Scope>()
        query.selectStandardAttributes.forEach { (scope, attrs) -> if (attrs.isNotEmpty()) scopesWithSelects.add(scope) }
        query.selectOtherAttributes.forEach { (scope, attrs) -> if (attrs.isNotEmpty()) scopesWithSelects.add(scope) }
        query.selectExpressions.forEach { (scope, exprs) -> if (exprs.isNotEmpty()) scopesWithSelects.add(scope) }
        query.selectAll.forEach { (scope, isAll) ->
            if (isAll == true) scopesWithSelects.add(scope)
        }
        query.isImplicitSelectAll.forEach { (scope, isImplicit) ->
            if (isImplicit == true) scopesWithSelects.add(scope)
        }

        // If no explicit scopes, use primary scope
        if (scopesWithSelects.isEmpty()) {
            val primaryScope = determinePrimaryScope(query)
            scopesWithSelects.add(primaryScope)
        }

        // Exclude EVENT scope if eventLimit == 0 (event wasn't matched in Cypher)
        if (eventLimit == 0) {
            scopesWithSelects.remove(com.processm.processminterpreter.pql.model.Scope.Event)
        }

        // Process each scope in order (LOG -> TRACE -> EVENT)
        val orderedScopes = scopesWithSelects.sortedBy { it.ordinal }

        for (modelScope in orderedScopes) {
            val scope = mapScope(modelScope)
            val nodeLabel = scopeToNodeLabel(scope)

            logger.debug("Building RETURN for scope=$scope, modelScope=$modelScope")
            logger.debug("selectAll=${query.selectAll[modelScope]}, isImplicitSelectAll=${query.isImplicitSelectAll[modelScope]}")
            logger.debug("selectStandardAttributes=${query.selectStandardAttributes[modelScope]?.map { it.name }}")
            logger.debug("selectOtherAttributes=${query.selectOtherAttributes[modelScope]?.map { it.name }}")

            // SELECT * or implicit SELECT * for this scope
            if (query.selectAll[modelScope] == true || query.isImplicitSelectAll[modelScope] == true) {
                allParts.add("properties($nodeLabel) as $nodeLabel")
                continue
            }

            // SELECT specific attributes for this scope
            // Standard attributes
            query.selectStandardAttributes[modelScope]?.forEach { attr ->
                // Use effective scope for hoisting
                val effectiveScope = mapScope(attr.effectiveScope ?: com.processm.processminterpreter.pql.model.Scope.Event)
                val effectiveNodeLabel = scopeToNodeLabel(effectiveScope)

                val cypherField = attributeToCypherField(attr, effectiveNodeLabel, effectiveScope)
                val prefix = when (attr.scope) {
                    com.processm.processminterpreter.pql.model.Scope.Event -> "e"
                    com.processm.processminterpreter.pql.model.Scope.Trace -> "t"
                    com.processm.processminterpreter.pql.model.Scope.Log -> "l"
                }
                val alias = "${prefix}_${attr.name.replace(":", "_")}"
                logger.debug("Standard attr: ${attr.name} -> $cypherField AS $alias")
                allParts.add("$cypherField AS $alias")
            }

            // Other attributes
            query.selectOtherAttributes[modelScope]?.forEach { attr ->
                // Use effective scope for hoisting
                val effectiveScope = mapScope(attr.effectiveScope ?: com.processm.processminterpreter.pql.model.Scope.Event)
                val effectiveNodeLabel = scopeToNodeLabel(effectiveScope)

                val cypherField = attributeToCypherField(attr, effectiveNodeLabel, effectiveScope)
                val prefix = when (attr.scope) {
                    com.processm.processminterpreter.pql.model.Scope.Event -> "e"
                    com.processm.processminterpreter.pql.model.Scope.Trace -> "t"
                    com.processm.processminterpreter.pql.model.Scope.Log -> "l"
                }
                val alias = "${prefix}_${attr.name.replace(":", "_")}"
                logger.debug("Other attr: ${attr.name} -> $cypherField AS $alias")
                allParts.add("$cypherField AS $alias")
            }

            // IMPORTANT: For TRACE scope with projected columns, always include traceId
            // This allows HierarchyReconstructor to extract trace name from traceId
            if (modelScope == com.processm.processminterpreter.pql.model.Scope.Trace) {
                val hasProjectedAttributes =
                    (query.selectStandardAttributes[modelScope]?.isNotEmpty() == true) ||
                    (query.selectOtherAttributes[modelScope]?.isNotEmpty() == true)

                if (hasProjectedAttributes && query.selectAll[modelScope] != true && query.isImplicitSelectAll[modelScope] != true) {
                    allParts.add("$nodeLabel.traceId AS t_traceId")
                    logger.debug("Added traceId for trace scope: $nodeLabel.traceId AS t_traceId")
                }
            }

            // Expressions (functions, etc.)
            query.selectExpressions[modelScope]?.forEach { expr ->
                val cypherExpr = translateExpressionToCypher(expr)
                // For expressions, we need a stable alias. 
                // Simple approach: use text representation, sanitized
                val alias = expr.toString().replace(Regex("[^a-zA-Z0-9_]"), "_")
                logger.debug("Expression: $expr -> $cypherExpr AS $alias")
                allParts.add("$cypherExpr AS $alias")
            }
        }

        // Always include trace/log identification when events are queried
        // without explicit trace/log attributes. This ensures HierarchyReconstructor
        // can properly group events into separate traces and logs.
        val hasEventScope = scopesWithSelects.contains(com.processm.processminterpreter.pql.model.Scope.Event)
        val hasTraceScope = scopesWithSelects.contains(com.processm.processminterpreter.pql.model.Scope.Trace)
        val hasLogScope = scopesWithSelects.contains(com.processm.processminterpreter.pql.model.Scope.Log)

        if (hasEventScope && !hasTraceScope) {
            if (!allParts.any { it.contains("t_traceId") }) {
                allParts.add("trace.traceId AS t_traceId")
            }
        }
        if (hasEventScope && !hasLogScope) {
            if (!allParts.any { it.contains("l_logId") }) {
                allParts.add("log.logId AS l_logId")
            }
        }

        logger.debug("Final RETURN parts: $allParts")

        return if (allParts.isEmpty()) {
            // Default: return all properties of primary scope
            val primaryScope = determinePrimaryScope(query)
            val scope = mapScope(primaryScope)
            val nodeLabel = scopeToNodeLabel(scope)
            "properties($nodeLabel) as $nodeLabel"
        } else {
            allParts.joinToString(", ")
        }
    }

    /**
     * Convert an Attribute to Cypher field reference.
     */
    private fun attributeToCypherField(
        attr: com.processm.processminterpreter.pql.model.Attribute,
        nodeLabel: String,
        targetScope: Scope,
    ): String {
        // Map attribute name to Neo4j property name using the target scope (handling hoisting)
        val propertyName = StandardAttributeMapper.translateToNeo4jProperty(attr.name, targetScope)

        // Neo4j requires backticks for property names with special characters (like colons)
        val escapedProperty = if (propertyName.contains(":")) {
            "`$propertyName`"
        } else {
            propertyName
        }

        return "$nodeLabel.$escapedProperty"
    }

    private fun buildOrderByClauseFromQuery(query: Query): List<OrderByItem>? {
        // Collect order by expressions from all scopes
        // Note: This might lose the relative order between scopes if they are mixed,
        // but the Query model currently stores them by scope.
        // We iterate in scope order (LOG -> TRACE -> EVENT).
        val allExpressions = mutableListOf<com.processm.processminterpreter.pql.model.OrderedExpression>()
        
        com.processm.processminterpreter.pql.model.Scope.values().forEach { scope ->
            query.orderByExpressions[scope]?.let { allExpressions.addAll(it) }
        }

        if (allExpressions.isEmpty()) return null

        return allExpressions.map { orderedExpr ->
            val cypherExpr = translateExpressionToCypher(orderedExpr.base)
            val direction =
                when (orderedExpr.direction) {
                    com.processm.processminterpreter.pql.model.OrderDirection.Ascending -> "ASC"
                    com.processm.processminterpreter.pql.model.OrderDirection.Descending -> "DESC"
                }
            OrderByItem(cypherExpr, direction)
        }
    }

    /**
     * offset: OFFSET offset_number (',' offset_number)*
     */
    override fun visitOffset(ctx: QLParser.OffsetContext): List<Int> = ctx.offset_number().map { visitOffset_number(it) as Int }

    override fun visitOffset_number(ctx: QLParser.Offset_numberContext): Int = ctx.NUMBER().text.toInt()

    // ========================================
    // CYPHER QUERY BUILDERS
    // ========================================

    data class OrderByItem(
        val expression: String,
        val direction: String,
    )

    @Deprecated("Not used - replaced by translateSelectQuery")
    private fun buildReadQuery(
        scope: Scope,
        selectClause: String,
        whereClause: String?,
        groupByClause: List<String>?,
        orderByClause: List<OrderByItem>?,
        limitClause: List<Int>?,
        offsetClause: List<Int>?,
    ): CypherQuery {
        val cypher = StringBuilder()
        val nodeLabel = scopeToNodeLabel(scope)

        // Build MATCH clause based on scope and logId
        cypher.append(buildMatchClause(scope))

        // WHERE clause
        if (whereClause != null || logId != null) {
            cypher.append(" WHERE ")
            val conditions = mutableListOf<String>()

            if (logId != null) {
                conditions.add("log.logId = \$logId")
                parameters["logId"] = logId
            }

            if (whereClause != null) {
                conditions.add(whereClause)
            }

            cypher.append(conditions.joinToString(" AND "))
        }

        // RETURN clause
        cypher.append(" RETURN ")
        if (selectClause == "*") {
            cypher.append("properties($nodeLabel) as $nodeLabel")
        } else {
            cypher.append(selectClause)
        }

        // ORDER BY
        if (orderByClause != null && orderByClause.isNotEmpty()) {
            cypher.append(" ORDER BY ")
            cypher.append(orderByClause.joinToString(", ") { "${it.expression} ${it.direction}" })
        }

        // SKIP (OFFSET)
        if (offsetClause != null && offsetClause.isNotEmpty()) {
            cypher.append(" SKIP ${offsetClause.first()}")
        }

        // LIMIT - This deprecated function doesn't support hierarchical limits
        // Use translateSelectQuery instead
        if (limitClause != null && limitClause.isNotEmpty()) {
            cypher.append(" LIMIT ${limitClause.first()}")
        }

        return CypherQuery(cypher.toString(), parameters.toMap())
    }

    @Deprecated("Not used - replaced by translateDeleteQuery")
    private fun buildDeleteQuery(
        scope: Scope,
        whereClause: String?,
        orderByClause: List<OrderByItem>?,
        limitClause: List<Int>?,
        offsetClause: List<Int>?,
    ): CypherQuery {
        val cypher = StringBuilder()
        val nodeLabel = scopeToNodeLabel(scope)

        // Build MATCH clause
        cypher.append(buildMatchClause(scope))

        // WHERE clause
        if (whereClause != null || logId != null) {
            cypher.append(" WHERE ")
            val conditions = mutableListOf<String>()

            if (logId != null) {
                conditions.add("log.logId = \$logId")
                parameters["logId"] = logId
            }

            if (whereClause != null) {
                conditions.add(whereClause)
            }

            cypher.append(conditions.joinToString(" AND "))
        }

        // For DELETE with LIMIT/ORDER, we need to collect IDs first
        if (limitClause != null || offsetClause != null || orderByClause != null) {
            // Use subquery to get limited set
            cypher.append(" WITH $nodeLabel")

            if (orderByClause != null && orderByClause.isNotEmpty()) {
                cypher.append(" ORDER BY ")
                cypher.append(orderByClause.joinToString(", ") { "${it.expression} ${it.direction}" })
            }

            if (offsetClause != null && offsetClause.isNotEmpty()) {
                cypher.append(" SKIP ${offsetClause.first()}")
            }

            if (limitClause != null && limitClause.isNotEmpty()) {
                cypher.append(" LIMIT ${limitClause.first()}")
            }
        }

        // DELETE clause
        cypher.append(" DELETE $nodeLabel")

        return CypherQuery(cypher.toString(), parameters.toMap())
    }

    private fun buildMatchClause(scope: Scope): String {
        // If no scopes were tracked yet, fall back to currentScope
        val scopesToInclude = if (usedScopes.isEmpty()) setOf(scope) else usedScopes

        // Determine which scopes to include in MATCH clause
        val needsLog = scopesToInclude.contains(Scope.Log) || logId != null
        val needsTrace = scopesToInclude.contains(Scope.Trace)
        val needsEvent = scopesToInclude.contains(Scope.Event)

        // Build MATCH clause from highest to lowest scope
        return when {
            // All three scopes needed
            needsLog && needsTrace && needsEvent -> {
                if (logId != null) {
                    "MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace) WITH log, trace MATCH (trace)-[:HAS_EVENT]->(event:Event)"
                } else {
                    "MATCH (log:Log)-[:CONTAINS]->(trace:Trace) WITH log, trace MATCH (trace)-[:HAS_EVENT]->(event:Event)"
                }
            }
            // LOG and TRACE
            needsLog && needsTrace -> {
                if (logId != null) {
                    "MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)"
                } else {
                    "MATCH (log:Log)-[:CONTAINS]->(trace:Trace)"
                }
            }
            // LOG and EVENT (unusual, but traverse through trace)
            needsLog && needsEvent -> {
                if (logId != null) {
                    "MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)-[:HAS_EVENT]->(event:Event)"
                } else {
                    "MATCH (log:Log)-[:CONTAINS]->(trace:Trace)-[:HAS_EVENT]->(event:Event)"
                }
            }
            // TRACE and EVENT
            needsTrace && needsEvent -> {
                if (logId != null) {
                    "MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)-[:HAS_EVENT]->(event:Event)"
                } else {
                    "MATCH (trace:Trace)-[:HAS_EVENT]->(event:Event)"
                }
            }
            // Only LOG
            needsLog -> {
                if (logId != null) {
                    "MATCH (log:Log {logId: \$logId})"
                } else {
                    "MATCH (log:Log)"
                }
            }
            // Only TRACE
            needsTrace -> {
                if (logId != null) {
                    "MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)"
                } else {
                    "MATCH (trace:Trace)"
                }
            }
            // Only EVENT (most common case)
            needsEvent -> {
                if (logId != null) {
                    "MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)-[:HAS_EVENT]->(event:Event)"
                } else {
                    "MATCH (event:Event)"
                }
            }
            // Fallback
            else -> "MATCH (event:Event)"
        }
    }

    // ========================================
    // HELPERS
    // ========================================

    private fun removeQuotes(str: String): String {
        var result = str
        // Remove scope prefix if present
        if (result.contains(":")) {
            result = result.substringAfter(":")
        }
        // Remove quotes
        return result.trim().removeSurrounding("'").removeSurrounding("\"")
    }

    private fun nextParamName(): String = "param${paramCounter++}"

    /**
     * Populate usedScopes set from Query object.
     */
    /**
     * Populate usedScopes set from Query object.
     */
    private fun populateUsedScopes(query: Query) {
        query.selectStandardAttributes.values.flatten().forEach { usedScopes.add(mapScope(it.effectiveScope ?: com.processm.processminterpreter.pql.model.Scope.Event)) }
        query.selectOtherAttributes.values.flatten().forEach { usedScopes.add(mapScope(it.effectiveScope ?: com.processm.processminterpreter.pql.model.Scope.Event)) }
        
        query.selectExpressions.values.flatten().forEach { collectScopesFromExpression(it) }
        
        query.selectAll.forEach { (scope, isAll) ->
            if (isAll == true) usedScopes.add(mapScope(scope))
        }
        query.isImplicitSelectAll.forEach { (scope, isImplicit) ->
            if (isImplicit == true) usedScopes.add(mapScope(scope))
        }
        
        // Also check WHERE clause for scopes
        if (query.whereExpression != com.processm.processminterpreter.pql.model.Expression.empty) {
            collectScopesFromExpression(query.whereExpression)
        }
    }

    private fun collectScopesFromExpression(expr: com.processm.processminterpreter.pql.model.IExpression) {
        when (expr) {
            is com.processm.processminterpreter.pql.model.Attribute -> usedScopes.add(mapScope(expr.effectiveScope ?: com.processm.processminterpreter.pql.model.Scope.Event))
            is com.processm.processminterpreter.pql.model.Function -> expr.children.forEach { collectScopesFromExpression(it) }
            is BinaryOperator -> {
                collectScopesFromExpression(expr.left)
                collectScopesFromExpression(expr.right)
            }
            is UnaryOperator -> collectScopesFromExpression(expr.operand)
            // Literals and others don't have scope dependencies
            else -> {}
        }
    }
}
