package com.processm.processminterpreter.xes

import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component
import java.io.OutputStream
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import java.util.zip.GZIPOutputStream

/**
 * Writer for XES (eXtensible Event Stream) format
 *
 * Serializes query results from Neo4j back to XES XML format
 * conforming to IEEE 1849-2016 XES Standard
 *
 * Reference: http://www.xes-standard.org/
 */
@Component
class XESWriter {
    private val logger = LoggerFactory.getLogger(XESWriter::class.java)

    // XES date format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    private val xesDateFormatter =
        DateTimeFormatter
            .ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSXXX")
            .withZone(ZoneOffset.UTC)

    /**
     * Write query results to XES format
     *
     * @param results Query results from Neo4j (list of records)
     * @param outputStream Target output stream
     * @param compress Whether to gzip compress the output
     * @param logName Optional log name (default: "Query Result Log")
     */
    fun writeXES(
        results: List<Map<String, Any?>>,
        outputStream: OutputStream,
        compress: Boolean = false,
        logName: String = "Query Result Log",
    ) {
        logger.info("Writing XES output: ${results.size} records, compress: $compress")

        val stream =
            if (compress) {
                GZIPOutputStream(outputStream)
            } else {
                outputStream
            }

        stream.use { out ->
            val writer = OutputStreamWriter(out, StandardCharsets.UTF_8)

            // Write XML declaration and root element
            writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n")
            writer.write("<!-- Generated by ProcessM Interpreter - Neo4j Implementation -->\n")
            writer.write("<!-- Conforms to XES Standard IEEE 1849-2016 -->\n")
            writer.write("<!-- Generated at: ${LocalDateTime.now()} -->\n")
            writer.write("<log xes.version=\"1.0\" xes.features=\"nested-attributes\" xmlns=\"http://www.xes-standard.org/\">\n")

            // Write extensions
            writeExtensions(writer)

            // Write log attributes
            writeLogAttributes(writer, logName)

            // Write global attributes
            writeGlobalAttributes(writer)

            // Write classifiers
            writeClassifiers(writer)

            // Group results by traces and write them
            val traces = groupByTraces(results)
            logger.debug("Grouped ${results.size} records into ${traces.size} traces")

            traces.forEach { (traceId, events) ->
                writeTrace(writer, traceId, events)
            }

            // Close log element
            writer.write("</log>\n")
            writer.flush()
        }

        logger.info("XES output written successfully")
    }

    /**
     * Write XES extensions
     */
    private fun writeExtensions(writer: OutputStreamWriter) {
        writer.write("\t<extension name=\"Concept\" prefix=\"concept\" uri=\"http://www.xes-standard.org/concept.xesext\"/>\n")
        writer.write("\t<extension name=\"Time\" prefix=\"time\" uri=\"http://www.xes-standard.org/time.xesext\"/>\n")
        writer.write("\t<extension name=\"Organizational\" prefix=\"org\" uri=\"http://www.xes-standard.org/org.xesext\"/>\n")
        writer.write("\t<extension name=\"Lifecycle\" prefix=\"lifecycle\" uri=\"http://www.xes-standard.org/lifecycle.xesext\"/>\n")
    }

    /**
     * Write log-level attributes
     */
    private fun writeLogAttributes(
        writer: OutputStreamWriter,
        logName: String,
    ) {
        writer.write("\t<string key=\"concept:name\" value=\"${escapeXml(logName)}\"/>\n")
        writer.write("\t<string key=\"source\" value=\"ProcessM Interpreter Neo4j\"/>\n")
        writer.write("\t<date key=\"created\" value=\"${formatDateTime(LocalDateTime.now())}\"/>\n")
    }

    /**
     * Write global attributes (default values for trace and event scopes)
     */
    private fun writeGlobalAttributes(writer: OutputStreamWriter) {
        writer.write("\t<global scope=\"trace\">\n")
        writer.write("\t\t<string key=\"concept:name\" value=\"__INVALID__\"/>\n")
        writer.write("\t</global>\n")

        writer.write("\t<global scope=\"event\">\n")
        writer.write("\t\t<string key=\"concept:name\" value=\"__INVALID__\"/>\n")
        writer.write("\t\t<string key=\"lifecycle:transition\" value=\"complete\"/>\n")
        writer.write("\t\t<date key=\"time:timestamp\" value=\"1970-01-01T01:00:00.000+01:00\"/>\n")
        writer.write("\t</global>\n")
    }

    /**
     * Write classifiers
     */
    private fun writeClassifiers(writer: OutputStreamWriter) {
        writer.write("\t<classifier name=\"Activity\" keys=\"concept:name\"/>\n")
        writer.write("\t<classifier name=\"Activity+Lifecycle\" keys=\"concept:name lifecycle:transition\"/>\n")
    }

    /**
     * Group results by trace ID
     *
     * Assumes each record has trace information (traceId or trace.traceId)
     */
    private fun groupByTraces(results: List<Map<String, Any?>>): Map<String, List<Map<String, Any?>>> =
        results.groupBy { record ->
            // Try different possible trace ID locations
            when {
                record.containsKey("traceId") -> {
                    record["traceId"]?.toString()
                }

                record.containsKey("caseId") -> {
                    record["caseId"]?.toString()
                }

                record.containsKey("t_traceId") -> {
                    record["t_traceId"]?.toString()
                }

                record.containsKey("trace_traceId") -> {
                    record["trace_traceId"]?.toString()
                }

                record.containsKey("t_caseId") -> {
                    record["t_caseId"]?.toString()
                }

                record.containsKey("trace_caseId") -> {
                    record["trace_caseId"]?.toString()
                }

                record.containsKey("trace") -> {
                    val trace = record["trace"]
                    when (trace) {
                        is Map<*, *> -> trace["traceId"]?.toString() ?: trace["caseId"]?.toString()
                        else -> null
                    }
                }

                record.containsKey("t") -> {
                    val trace = record["t"]
                    when (trace) {
                        is Map<*, *> -> trace["traceId"]?.toString() ?: trace["caseId"]?.toString()
                        else -> null
                    }
                }

                else -> {
                    null
                }
            } ?: "unknown-trace-${System.currentTimeMillis()}"
        }

    /**
     * Write a single trace with its events
     */
    private fun writeTrace(
        writer: OutputStreamWriter,
        traceId: String,
        events: List<Map<String, Any?>>,
    ) {
        writer.write("\t<trace>\n")

        // Write trace attributes
        writer.write("\t\t<string key=\"concept:name\" value=\"${escapeXml(traceId)}\"/>\n")

        // Extract and write trace-level attributes from first event (if available)
        val firstEvent = events.firstOrNull()
        firstEvent?.let { event ->
            val trace = event["trace"] ?: event["t"]
            toStringMap(trace)?.let { traceMap ->
                writeAttributes(writer, traceMap, level = 2, excludeKeys = setOf("traceId", "id", "labels"))
            }
        }

        // Write events (sorted by timestamp if available)
        val sortedEvents =
            events.sortedBy { event ->
                extractTimestamp(event)
            }

        sortedEvents.forEach { event ->
            writeEvent(writer, event)
        }

        writer.write("\t</trace>\n")
    }

    /**
     * Write a single event
     */
    private fun writeEvent(
        writer: OutputStreamWriter,
        event: Map<String, Any?>,
    ) {
        writer.write("\t\t<event>\n")

        // Extract event data (might be nested under "event" or "e" key)
        val eventData =
            when {
                event.containsKey("event") -> toStringMap(event["event"]) ?: event
                event.containsKey("e") -> toStringMap(event["e"]) ?: event
                else -> event
            }

        // Write standard XES attributes
        val activity = eventData["activity"]?.toString() ?: eventData["concept:name"]?.toString() ?: "Unknown Activity"
        writer.write("\t\t\t<string key=\"concept:name\" value=\"${escapeXml(activity)}\"/>\n")

        // Timestamp
        val timestamp = eventData["timestamp"] ?: eventData["time:timestamp"]
        if (timestamp != null) {
            val formattedTimestamp =
                when (timestamp) {
                    is LocalDateTime -> formatDateTime(timestamp)
                    is java.time.ZonedDateTime -> timestamp.format(xesDateFormatter)
                    is String -> timestamp
                    else -> timestamp.toString()
                }
            writer.write("\t\t\t<date key=\"time:timestamp\" value=\"$formattedTimestamp\"/>\n")
        }

        // Resource
        val resource = eventData["resource"] ?: eventData["org:resource"]
        if (resource != null) {
            writer.write("\t\t\t<string key=\"org:resource\" value=\"${escapeXml(resource.toString())}\"/>\n")
        }

        // Lifecycle
        val lifecycle = eventData["lifecycle"] ?: eventData["lifecycle:transition"] ?: "complete"
        writer.write("\t\t\t<string key=\"lifecycle:transition\" value=\"${escapeXml(lifecycle.toString())}\"/>\n")

        // Cost (if present)
        val cost = eventData["cost"] ?: eventData["cost:total"]
        if (cost != null) {
            val costVal = cost.toString().toDoubleOrNull() ?: cost
            writer.write("\t\t\t<float key=\"cost:total\" value=\"$costVal\"/>\n")
        }

        // Other attributes
        writeAttributes(
            writer,
            eventData,
            level = 3,
            excludeKeys =
                setOf(
                    "id",
                    "eventId",
                    "activity",
                    "timestamp",
                    "resource",
                    "lifecycle",
                    "cost",
                    "concept:name",
                    "time:timestamp",
                    "org:resource",
                    "lifecycle:transition",
                    "cost:total",
                    "labels",
                    "createdAt",
                ),
        )

        writer.write("\t\t</event>\n")
    }

    /**
     * Write custom attributes
     */
    private fun writeAttributes(
        writer: OutputStreamWriter,
        data: Map<String, Any?>,
        level: Int,
        excludeKeys: Set<String> = emptySet(),
    ) {
        val indent = "\t".repeat(level)

        data.forEach { (key, value) ->
            if (key !in excludeKeys && value != null) {
                when (value) {
                    is String -> {
                        writer.write("$indent<string key=\"${escapeXml(key)}\" value=\"${escapeXml(value)}\"/>\n")
                    }

                    is Int, is Long -> {
                        writer.write("$indent<int key=\"${escapeXml(key)}\" value=\"$value\"/>\n")
                    }

                    is Float, is Double -> {
                        writer.write("$indent<float key=\"${escapeXml(key)}\" value=\"$value\"/>\n")
                    }

                    is Boolean -> {
                        writer.write("$indent<boolean key=\"${escapeXml(key)}\" value=\"$value\"/>\n")
                    }

                    is LocalDateTime -> {
                        writer.write("$indent<date key=\"${escapeXml(key)}\" value=\"${formatDateTime(value)}\"/>\n")
                    }

                    is Map<*, *> -> {
                        // Nested attributes - convert to string
                        writer.write("$indent<string key=\"${escapeXml(key)}\" value=\"${escapeXml(value.toString())}\"/>\n")
                    }

                    else -> {
                        // Other types - convert to string
                        writer.write("$indent<string key=\"${escapeXml(key)}\" value=\"${escapeXml(value.toString())}\"/>\n")
                    }
                }
            }
        }
    }

    /**
     * Safely cast Any? to Map<String, Any?> with type checking
     */
    @Suppress("UNCHECKED_CAST")
    private fun toStringMap(value: Any?): Map<String, Any?>? =
        when {
            value == null -> {
                null
            }

            value is Map<*, *> -> {
                // Validate that keys are strings
                if (value.keys.all { it is String }) {
                    value as Map<String, Any?>
                } else {
                    null
                }
            }

            else -> {
                null
            }
        }

    /**
     * Extract timestamp from event for sorting
     */
    private fun extractTimestamp(event: Map<String, Any?>): LocalDateTime? {
        val eventData =
            when {
                event.containsKey("event") -> toStringMap(event["event"]) ?: event
                event.containsKey("e") -> toStringMap(event["e"]) ?: event
                else -> event
            }

        val timestamp = eventData["timestamp"] ?: eventData["time:timestamp"]
        return when (timestamp) {
            is LocalDateTime -> timestamp
            else -> null
        }
    }

    /**
     * Format LocalDateTime to XES date format
     */
    private fun formatDateTime(dateTime: LocalDateTime): String = dateTime.atZone(ZoneOffset.UTC).format(xesDateFormatter)

    /**
     * Escape XML special characters
     */
    private fun escapeXml(text: String): String =
        text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
}

/**
 * Exception thrown when XES writing fails
 */
class XESWriteException(
    message: String,
    cause: Throwable? = null,
) : RuntimeException(message, cause)
